import type { ExpansionProject, VolunteerTeacher } from "./types"


export const MOCK_VOLUNTEER_DATA: VolunteerTeacher[] = [
    {
        id: "1",
        schoolName: "Bangkok International School",
        subject: "Mathematics",
        timeline: "Jan 15 - Mar 15, 2025",
        latitude: 13.7455,
        longitude: 100.5677,
    },
    {
        id: "2",
        schoolName: "Sanam Luang School",
        subject: "English",
        timeline: "Jan 20 - Apr 20, 2025",
        latitude: 13.7513,
        longitude: 100.4933,
    },
    {
        id: "3",
        schoolName: "Assumption University",
        subject: "Science",
        timeline: "Feb 1 - May 1, 2025",
        latitude: 13.8109,
        longitude: 100.7755,
    },
    {
        id: "4",
        schoolName: "St. Andrews International School",
        subject: "History",
        timeline: "Jan 10 - Mar 10, 2025",
        latitude: 13.7226,
        longitude: 100.5725,
    },
    {
        id: "5",
        schoolName: "Chulalongkorn University",
        subject: "Physics",
        timeline: "Feb 15 - Apr 15, 2025",
        latitude: 13.7357,
        longitude: 100.5331,
    },
    {
        id: "6",
        schoolName: "Pathumwan Princess School",
        subject: "Chemistry",
        timeline: "Jan 25 - Mar 25, 2025",
        latitude: 13.7448,
        longitude: 100.5416,
    },
    {
        id: "7",
        schoolName: "Thonburi School",
        subject: "Biology",
        timeline: "Mar 1 - May 1, 2025",
        latitude: 13.6931,
        longitude: 100.4908,
    },
    {
        id: "8",
        schoolName: "Petchyindee School",
        subject: "Art",
        timeline: "Feb 10 - Apr 10, 2025",
        latitude: 13.7289,
        longitude: 100.5245,
    },
    {
        id: "9",
        schoolName: "Debsirin School",
        subject: "Thai Language",
        timeline: "Jan 15 - Mar 15, 2025",
        latitude: 13.7456,
        longitude: 100.5032,
    },
    {
        id: "10",
        schoolName: "Ramathibodi School",
        subject: "Physical Education",
        timeline: "Feb 5 - Apr 5, 2025",
        latitude: 13.7535,
        longitude: 100.5275,
    },
    {
        id: "11",
        schoolName: "Satri Si Suriyothai School",
        subject: "Computer Science",
        timeline: "Jan 20 - Mar 20, 2025",
        latitude: 13.7289,
        longitude: 100.4945,
    },
    {
        id: "12",
        schoolName: "Sukhothai Thammathirat School",
        subject: "Music",
        timeline: "Feb 8 - Apr 8, 2025",
        latitude: 13.6245,
        longitude: 100.5156,
    },
    {
        id: "13",
        schoolName: "Nunnery School",
        subject: "English",
        timeline: "Jan 30 - Mar 30, 2025",
        latitude: 13.7612,
        longitude: 100.5423,
    },
    {
        id: "14",
        schoolName: "Rangsit School",
        subject: "Mathematics",
        timeline: "Feb 12 - Apr 12, 2025",
        latitude: 13.8456,
        longitude: 100.6123,
    },
    {
        id: "15",
        schoolName: "St. Gabriel's College",
        subject: "English Literature",
        timeline: "Jan 18 - Mar 18, 2025",
        latitude: 13.7312,
        longitude: 100.5567,
    },
]


export const MOCK_EXPANSION_DATA: ExpansionProject[] = [
    {
        id: "1",
        schoolName: "Chiang Mai Educational Center",
        district: "เชียงใหม่",
        region: "north",
        projectName: "Expansion",
        startDate: "2025-01-15",
        endDate: "2025-06-30",
    },
    {
        id: "2",
        schoolName: "Chiang Rai Learning Hub",
        district: "เชียงราย",
        region: "north",
        projectName: "Expansion",
        startDate: "2025-02-01",
        endDate: "2025-07-15",
    },
    {
        id: "3",
        schoolName: "Phayao Primary School",
        district: "พะเยา",
        region: "north",
        projectName: "Expansion",
        startDate: "2025-01-20",
        endDate: "2025-05-30",
    },
    {
        id: "4",
        schoolName: "Phrae Community School",
        district: "แพร่",
        region: "north",
        projectName: "Expansion",
        startDate: "2025-02-10",
        endDate: "2025-06-20",
    },
    {
        id: "5",
        schoolName: "Nan District Academy",
        district: "น่าน",
        region: "north",
        projectName: "Expansion",
        startDate: "2025-01-25",
        endDate: "2025-07-10",
    },
    {
        id: "6",
        schoolName: "Uttaradit School",
        district: "อุตรดิตถ์",
        region: "north",
        projectName: "Expansion",
        startDate: "2025-02-15",
        endDate: "2025-06-30",
    },
    {
        id: "7",
        schoolName: "Lampang Teachers Institute",
        district: "ลำปาง",
        region: "north",
        projectName: "Expansion",
        startDate: "2025-01-10",
        endDate: "2025-05-20",
    },
    {
        id: "8",
        schoolName: "Lamphun Educational Center",
        district: "ลำพูน",
        region: "north",
        projectName: "Expansion",
        startDate: "2025-02-05",
        endDate: "2025-06-15",
    },
    {
        id: "9",
        schoolName: "Sukhothai Historic School",
        district: "สุโขทัย",
        region: "northeast",
        projectName: "Expansion",
        startDate: "2025-01-30",
        endDate: "2025-07-05",
    },
    {
        id: "10",
        schoolName: "Phitsanulok Community Learning",
        district: "พิษณุโลก",
        region: "northeast",
        projectName: "Expansion",
        startDate: "2025-02-12",
        endDate: "2025-06-25",
    },
    {
        id: "11",
        schoolName: "Phetchabun District School",
        district: "เพชรบูรณ์",
        region: "northeast",
        projectName: "Expansion",
        startDate: "2025-01-18",
        endDate: "2025-05-28",
    },
    {
        id: "12",
        schoolName: "Kamphaeng Phet Academy",
        district: "กำแพงเพชร",
        region: "northeast",
        projectName: "Expansion",
        startDate: "2025-02-08",
        endDate: "2025-06-22",
    },
    {
        id: "13",
        schoolName: "Satun Educational Institute",
        district: "สตูล",
        region: "southern",
        projectName: "Expansion",
        startDate: "2025-03-01",
        endDate: "2025-08-15",
    },
    {
        id: "14",
        schoolName: "Songkhla Learning Center",
        district: "สงขลา",
        region: "southern",
        projectName: "Expansion",
        startDate: "2025-02-20",
        endDate: "2025-07-30",
    },
    {
        id: "15",
        schoolName: "Nakhon Si Thammarat School",
        district: "นครศรีธรรมราช",
        region: "central",
        projectName: "Expansion",
        startDate: "2025-01-28",
        endDate: "2025-06-30",
    },
    {
        id: "16",
        schoolName: "Surat Thani Community School",
        district: "สุราษฎร์ธานี",
        region: "central",
        projectName: "Expansion",
        startDate: "2025-02-03",
        endDate: "2025-07-15",
    },
    {
        id: "17",
        schoolName: "Phangnga Teachers Academy",
        district: "พังงา",
        region: "southern",
        projectName: "Expansion",
        startDate: "2025-02-18",
        endDate: "2025-07-20",
    },
    {
        id: "18",
        schoolName: "Phuket International School",
        district: "ภูเก็ต",
        region: "southern",
        projectName: "Expansion",
        startDate: "2025-01-05",
        endDate: "2025-06-10",
    },
    {
        id: "19",
        schoolName: "Krabi District Learning Hub",
        district: "กระบี่",
        region: "southern",
        projectName: "Expansion",
        startDate: "2025-02-25",
        endDate: "2025-07-25",
    },
    {
        id: "20",
        schoolName: "Chanthaburi Educational Center",
        district: "จันทบุรี",
        region: "eastern",
        projectName: "Expansion",
        startDate: "2025-01-22",
        endDate: "2025-06-18",
    },
]

