import type { Metadata } from "next";
import "./globals.css";
import HamburgerMenu from "./components/HamburgerMenu";
import { fcLamoon } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={fcLamoon.variable}>
      <body
        className={`${fcLamoon.variable} antialiased`}
      >
        <HamburgerMenu />
        {children}
      </body>
    </html>
  );
}
